### ISSUE TITLE
WHMCS module throws error

### ISSUE THREAD

**Issue by ammarahsan619** [namesilo/whmcs#14]
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

For additional assistance, please reference the [WHMCS TroubleShooting Guide »](https://docs.whmcs.com/Troubleshooting_Guide)

TypeError: Cannot access offset of type string on string in /home/orbithoster/public_html/services.orbithoster.pk/modules/registrars/namesilo/namesilo.php:267
Stack trace:
#0 /home/orbithoster/public_html/services.orbithoster.pk/modules/registrars/namesilo/namesilo.php(490): namesilo_transactionCall('getRegistrarLoc...', 'https://www.nam...', Array)
#1 [internal function]: namesilo_GetRegistrarLock(Array)
#2 /home/orbithoster/public_html/services.orbithoster.pk/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('namesilo_GetReg...', Array)
#3 /home/orbithoster/public_html/services.orbithoster.pk/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call('GetRegistrarLoc...', Array)
#4 /home/orbithoster/public_html/services.orbithoster.pk/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\Module\Registrar->call('GetRegistrarLoc...', Array)
#5 /home/orbithoster/public_html/services.orbithoster.pk/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\Domains->moduleCall('GetRegistrarLoc...')
#6 /home/orbithoster/public_html/services.orbithoster.pk/admin/clientsdomains.php(0): WHMCS\Domains->getDomainInformation()
#7 {main}

**Comment by jas8522** [comment]
Seems like that should only happen if you have debug mode on. Even so, I've modified our fork to include a fix for this if you want to give that a try: https://github.com/websavers/WHMCS-NameSilo

**Comment by namesilo** [comment]
fixed in "error when debug mode enabled" commit:
https://github.com/namesilo/whmcs/commit/2256faf5c6114c8a99e3d065924a7ae22a5ba0ae
