### ISSUE TITLE
WHMCS 8.9v broken

### ISSUE THREAD

**Issue by A7U** [namesilo/whmcs#19]
Hi,

The module hasn't been updated since WHMCS 8.1, and stopped working after upgrading from WHMCS 8.7 to 8.9.
Could you please look into it?
The error I'm getting at the moment is the following when managing the domain in the admin area:
Error: TypeError: Cannot access offset of type string on string in /home/admin/domains/XXX/public_html/billing/modules/registrars/namesilo/namesilo.php:267 Stack trace: #0 /home/admin/domains/XXX/public_html/billing/modules/registrars/namesilo/namesilo.php(490): namesilo_transactionCall() #1 [internal function]: namesilo_GetRegistrarLock() #2 /home/admin/domains/XXX/public_html/billing/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func() #3 /home/admin/domains/XXX/public_html/billing/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call() #4 /home/admin/domains/XXX/public_html/billing/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\Module\Registrar->call() #5 /home/admin/domains/XXX/public_html/billing/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\Domains->moduleCall() #6 /home/admin/domains/XXX/public_html/billing/admin/clientsdomains.php(0): WHMCS\Domains->getDomainInformation() #7 {main}

**Comment by mrEckendonk** [comment]
same here

**Comment by ominocity** [comment]
Has this been fixed?

**Comment by namesilo** [comment]
fixed in "error when debug mode enabled" commit:
https://github.com/namesilo/whmcs/commit/2256faf5c6114c8a99e3d065924a7ae22a5ba0ae
