### ISSUE TITLE
I am facing a problem with version 8.10.1. This message appears when I view domain information from the client or administrator control panel. 

### ISSUE THREAD

**Issue by nader0yasser** [namesilo/whmcs#20]
I am facing a problem with version 8.10.1. This message appears when I view domain information from the client or administrator control panel. 
Is there a solution?

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

For additional assistance, please reference the [WHMCS TroubleShooting Guide »](https://docs.whmcs.com/Troubleshooting_Guide)

Error: Class "Domain" not found in /home/tarweigc/public_html/clients.tarweig.com/modules/registrars/namesilo/namesilo.php:381
Stack trace:
#0 [internal function]: namesilo_GetDomainInformation()
#1 /home/tarweigc/public_html/clients.tarweig.com/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func()
#2 /home/tarweigc/public_html/clients.tarweig.com/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call()
#3 /home/tarweigc/public_html/clients.tarweig.com/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\Module\Registrar->call()
#4 /home/tarweigc/public_html/clients.tarweig.com/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\Domains->moduleCall()
#5 /home/tarweigc/public_html/clients.tarweig.com/admin/clientsdomains.php(0): WHMCS\Domains->getDomainInformation()
#6 {main}

**Comment by corozanu** [comment]
Any news ?

**Comment by nader0yasser** [comment]
The problem was solved and it is now working fine

**Comment by nader0yasser** [comment]
I am using this version (fix undefined class domain issue
author
Pavel Gorbatsevich
committed
on Oct 2 ) from the file (namesilo.php) It works well

**Comment by namesilo** [comment]
fixed in "fix undefined class domain issue" commit:
https://github.com/namesilo/whmcs/commit/3ec96156d90b81bc17f6c84b377afb646dbb70d4
