### ISSUE TITLE
ERROR while using namesilo WHMCS module

### ISSUE THREAD

**Issue by corozanu** [namesilo/whmcs#21]
WHMCS 8.11.2
PHP 8.1

TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/vhosts/domain.com/subdomains/subdomain.domain.com/vendor/whmcs/whmcs-foundation/lib/Domain/Registrar/Domain.php:0
Stack trace:
#0 /var/www/vhosts/domain.com/subdomains/subdomain.domain.com/vendor/whmcs/whmcs-foundation/lib/Domain/Registrar/Domain.php(0): count()
#1 /var/www/vhosts/domain.com/subdomains/subdomain.domain.com/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\Domain\Registrar\Domain->hasNameservers()
#2 /var/www/vhosts/domain.com/subdomains/subdomain.domain.com/vbit/clientsdomains.php(0): WHMCS\Domains->getDomainInformation()
#3 {main}

**Comment by MarkCanada** [comment]
Same problem here - but only with .CA domains - one is in transfer, the other one I wanted to transfer through WHMCS.
.COM work well.

**Comment by MarkCanada** [comment]
The domain transfer completed and it shows up now in WHMCS without error.

It seems that maybe this problem comes up if the domain is not available in NameSilo yet? 
Like during a transfer or when we want to switch it to NameSilo to start a transfer.

So far I have only tested it with .CA

**Comment by abdullqadeer** [comment]
Hello There, 

Any work around to fix this prob, my .com domains with Pending Transfer , Pending Registration and Transferred Away status throwing this error. This started to be appeared in last module update.

**Comment by jstebenne** [comment]
I have the same problem with .COM domains that are being transferred

**Comment by namesilo** [comment]
fixed in "countable fix" commit:
https://github.com/namesilo/whmcs/commit/a4ffbc7832def15840ab73d1e91f9bcb59673094
